package com.ammacias.tectium.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORIA_DB".
 */
@Entity
public class CategoriaDB {

    @Id(autoincrement = true)
    private Long id;
    private String nombre;
    private String descripcion;
    private String tag;

    @Generated
    public CategoriaDB() {
    }

    public CategoriaDB(Long id) {
        this.id = id;
    }

    @Generated
    public CategoriaDB(Long id, String nombre, String descripcion, String tag) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.tag = tag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

}
